//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JKMServices.DAL
{
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JKMServices.DAL.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to jkmoving_customernumber,firstname,lastname,onerivet_verificationcode, onerivet_codevalidtill,onerivet_termsagreed,onerivet_receivenotification, onerivet_iscustomerregistered,onerivet_passwordhash,onerivet_passwordsalt,telephone1, emailaddress1, preferredcontactmethodcode,onerivet_receivenotification.
        ///   Looks up a localized string similar to activityid,_regardingobjectid_value,subject,description,actualstart,actualend,onerivet_notificationtype,
        ///statecode.
        /// </summary>
        internal static string activityGetAlertListFields
        {
            get
            {
                return ResourceManager.GetString("activityGetAlertListFields", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to jkmoving_customernumber, fullname, onerivet_verificationcode, onerivet_codevalidtill, onerivet_termsagreed, onerivet_receivenotification, onerivet_iscustomerregistered, 
        ///onerivet_passwordhash, onerivet_passwordsalt, telephone1, emailaddress1, preferredcontactmethodcode.
        /// </summary>
        internal static string contactProfileDataFields
        {
            get
            {
                return ResourceManager.GetString("contactProfileDataFields", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to jkmoving_customernumber, onerivet_verificationcode, onerivet_codevalidtill, 
        ///onerivet_passwordhash, onerivet_passwordsalt.
        /// </summary>
        internal static string contactVerificationDataFields
        {
            get
            {
                return ResourceManager.GetString("contactVerificationDataFields", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to statecode eq 0.
        /// </summary>
        internal static string crm_ActiveRecordFilter
        {
            get
            {
                return ResourceManager.GetString("crm_ActiveRecordFilter", resourceCulture);
            }
        }
        ///   Looks up a localized string similar to actualstart.
        /// </summary>
        internal static string crm_activity_actualstart
        {
            get
            {
                return ResourceManager.GetString("crm_activity_actualstart", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to _regardingobjectid_value.
        /// </summary>
        internal static string crm_activity_regardingobjectidvalue
        {
            get
            {
                return ResourceManager.GetString("crm_activity_regardingobjectidvalue", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to CRM connection is lost..
        /// </summary>
        internal static string CRM_ConnectionLost
        {
            get
            {
                return ResourceManager.GetString("CRM_ConnectionLost", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to fullname.
        /// </summary>
        internal static string crm_contact_customerFullName
        {
            get
            {
                return ResourceManager.GetString("crm_contact_customerFullName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to contactid.
        /// </summary>
        internal static string crm_contact_customerId
        {
            get
            {
                return ResourceManager.GetString("crm_contact_customerId", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to jkmoving_customernumber.
        /// </summary>
        internal static string crm_contact_customerNumber
        {
            get
            {
                return ResourceManager.GetString("crm_contact_customerNumber", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to emailaddress1.
        /// </summary>
        internal static string crm_contact_customerPrimaryEmail
        {
            get
            {
                return ResourceManager.GetString("crm_contact_customerPrimaryEmail", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to contacts.
        /// </summary>
        internal static string crm_contact_entityName
        {
            get
            {
                return ResourceManager.GetString("crm_contact_entityName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to onerivet_iscustomerregistered.
        /// </summary>
        internal static string crm_contact_iscustomerregistered
        {
            get
            {
                return ResourceManager.GetString("crm_contact_iscustomerregistered", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to telephone1.
        /// </summary>
        internal static string crm_contact_phoneNumber
        {
            get
            {
                return ResourceManager.GetString("crm_contact_phoneNumber", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to nodus_securitycode.
        /// </summary>
        internal static string crm_nodus_payfabricsecuritycode_deviceID
        {
            get
            {
                return ResourceManager.GetString("crm_nodus_payfabricsecuritycode_deviceID", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to CONTENT.
        /// </summary>
        internal static string CRM_RESPONSE_CONTENT
        {
            get
            {
                return ResourceManager.GetString("CRM_RESPONSE_CONTENT", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to FAIL.
        /// </summary>
        internal static string CRM_RESPONSE_FAIL
        {
            get
            {
                return ResourceManager.GetString("CRM_RESPONSE_FAIL", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to INFORMATION.
        /// </summary>
        internal static string CRM_RESPONSE_INFORMATION
        {
            get
            {
                return ResourceManager.GetString("CRM_RESPONSE_INFORMATION", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to STATUS.
        /// </summary>
        internal static string CRM_RESPONSE_STATUS
        {
            get
            {
                return ResourceManager.GetString("CRM_RESPONSE_STATUS", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to SUCCESS.
        /// </summary>
        internal static string CRM_RESPONSE_SUCCESS
        {
            get
            {
                return ResourceManager.GetString("CRM_RESPONSE_SUCCESS", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string CRM_STATUS_200
        {
            get
            {
                return ResourceManager.GetString("CRM_STATUS_200", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 204 - NoContent.
        /// </summary>
        internal static string CRM_STATUS_204
        {
            get
            {
                return ResourceManager.GetString("CRM_STATUS_204", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 206 - Partial Content..
        /// </summary>
        internal static string CRM_STATUS_206
        {
            get
            {
                return ResourceManager.GetString("CRM_STATUS_206", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 400 - Bad Request..
        /// </summary>
        internal static string CRM_STATUS_400
        {
            get
            {
                return ResourceManager.GetString("CRM_STATUS_400", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unauthorized.
        /// </summary>
        internal static string CRM_STATUS_401
        {
            get
            {
                return ResourceManager.GetString("CRM_STATUS_401", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to NotFound.
        /// </summary>
        internal static string CRM_STATUS_404
        {
            get
            {
                return ResourceManager.GetString("CRM_STATUS_404", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 503 - CRM Service is currently unavailable.
        /// </summary>
        internal static string CRM_STATUS_503
        {
            get
            {
                return ResourceManager.GetString("CRM_STATUS_503", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to DELETE Alerts where AlertID IN (@alertIdList).
        /// </summary>
        internal static string deleteAlertList
        {
            get
            {
                return ResourceManager.GetString("deleteAlertList", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to delete from Customers where CustomerId=@CustomerId.
        /// </summary>
        internal static string deleteCustomerDetails
        {
            get
            {
                return ResourceManager.GetString("deleteCustomerDetails", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to select AlertID, CustomerID, AlertTitle, AlertDescription, StartDate, EndDate, DisplayInCalendar, ActionToTake, AlertType, IsActive
        ///from Alerts where IsActive = 1 and CustomerID =@CustomerID and CONVERT(VARCHAR(10), StartDate, 101) &gt;=CAST(CONVERT(VARCHAR(10), ISNULL(@StartDate,StartDate), 101) as date).
        /// </summary>
        internal static string getAlertList
        {
            get
            {
                return ResourceManager.GetString("getAlertList", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to select CustomerId from  Customers where EmailID in(@EmailId,@EmailId1,@EmailId2).
        /// </summary>
        internal static string getCustomerDetails
        {
            get
            {
                return ResourceManager.GetString("getCustomerDetails", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to select DocumentID,DocumentTitle from Documents where MoveID=@MoveID.
        /// </summary>
        internal static string GetCustomerDocumentList
        {
            get
            {
                return ResourceManager.GetString("GetCustomerDocumentList", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to select EmailID from  Customers where CustomerId=@CustomerId.
        /// </summary>
        internal static string getCustomerEmailById
        {
            get
            {
                return ResourceManager.GetString("getCustomerEmailById", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to SELECT CustomerId, IsCustomerRegistered FROM Customers WHERE EmailID=@EmailId.
        /// </summary>
        internal static string getCustomerIdByEmail
        {
            get
            {
                return ResourceManager.GetString("getCustomerIdByEmail", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM Customers where CustomerId=@CustomerId.
        /// </summary>
        internal static string getCustomerProfileData
        {
            get
            {
                return ResourceManager.GetString("getCustomerProfileData", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to SELECT EmailID, PasswordHash, PasswordSalt, VerificationCode, CodeValidTill, IsCustomerRegistered
        ///FROM Customers 
        ///WHERE CustomerId=@CustomerId AND CodeValidTill &gt;= CONVERT(VARCHAR(10), GETDATE(), 101).
        /// </summary>
        internal static string getCustomerVerificationData
        {
            get
            {
                return ResourceManager.GetString("getCustomerVerificationData", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to select MoveID,DocumentTitle,DocumentType from Documents where DocumentID=@DocumentID.
        /// </summary>
        internal static string GetDocumentData
        {
            get
            {
                return ResourceManager.GetString("GetDocumentData", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to SELECT TOP 1 AlertID
        ///FROM Alerts
        ///order by AlertID desc.
        /// </summary>
        internal static string getLastPrimaryKeyField
        {
            get
            {
                return ResourceManager.GetString("getLastPrimaryKeyField", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to select CustomerId from Customers where IsCustomerRegistered=@IsCustomerRegistered and CustomerId=@CustomerId.
        /// </summary>
        internal static string GetRegisteredCustomer
        {
            get
            {
                return ResourceManager.GetString("GetRegisteredCustomer", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO Alerts
        ///           (AlertID
        ///           ,CustomerID
        ///           ,AlertTitle
        ///           ,AlertDescription
        ///           ,StartDate
        ///           ,EndDate
        ///           ,DisplayInCalendar
        ///           ,ActionToTake
        ///           ,AlertType
        ///           ,IsActive)
        ///     VALUES
        ///           (@AlertID,
        ///            @CustomerID,
        ///            @AlertTitle,
        ///            @AlertDescription,
        ///            @StartDate,
        ///            @EndDate,
        ///            @DisplayInCalendar,
        ///            @ActionToTake,
        ///            @Aler [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string insertAlertDetails
        {
            get
            {
                return ResourceManager.GetString("insertAlertDetails", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to DTO mapped successfully..
        /// </summary>
        internal static string logDTOMapped
        {
            get
            {
                return ResourceManager.GetString("logDTOMapped", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Method Encountered.
        /// </summary>
        internal static string logMethodEncountered
        {
            get
            {
                return ResourceManager.GetString("logMethodEncountered", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 676860000.
        /// </summary>
        internal static string Move_StatusReasonCode_Estimated
        {
            get
            {
                return ResourceManager.GetString("Move_StatusReasonCode_Estimated", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to jkmoving_destination_line1, jkmoving_destination_line2, jkmoving_destination_city, jkmoving_destination_stateorprovince, jkmoving_destination_postalcode, jkmoving_destination_country, jkmoving_destination_contactname, jkmoving_destination_telephone1, jkmoving_destination_telephone3, jkmoving_destination_telephone2.
        /// </summary>
        internal static string moveDestinationAddressFields
        {
            get
            {
                return ResourceManager.GetString("moveDestinationAddressFields", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to jkmoving_origin_line1, jkmoving_origin_line2, jkmoving_origin_city, jkmoving_origin_stateorprovince, jkmoving_origin_postalcode, jkmoving_origin_country, jkmoving_origin_contactname, jkmoving_origin_telephone1, jkmoving_origin_telephone3, jkmoving_origin_telephone2.
        /// </summary>
        internal static string moveOriginAddressFields
        {
            get
            {
                return ResourceManager.GetString("moveOriginAddressFields", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to CustomerID is successfully retrieved..
        /// </summary>
        internal static string msgCustomerIdRetrieved
        {
            get
            {
                return ResourceManager.GetString("msgCustomerIdRetrieved", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Customer does not exists or invalid..
        /// </summary>
        internal static string msgCustomerNotExistsOrInvalid
        {
            get
            {
                return ResourceManager.GetString("msgCustomerNotExistsOrInvalid", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Document does not exists..
        /// </summary>
        internal static string msgDocumentDoesNotExists
        {
            get
            {
                return ResourceManager.GetString("msgDocumentDoesNotExists", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Error occured in DateTime conversion..
        /// </summary>
        internal static string msgErrorInDateConversion
        {
            get
            {
                return ResourceManager.GetString("msgErrorInDateConversion", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Error occured in verification process..
        /// </summary>
        internal static string msgErrorInVerificationProcess
        {
            get
            {
                return ResourceManager.GetString("msgErrorInVerificationProcess", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Issue occured while retrieving Customer detail..
        /// </summary>
        internal static string msgErrorOccuredInGettingCustomerID
        {
            get
            {
                return ResourceManager.GetString("msgErrorOccuredInGettingCustomerID", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to save the details..
        /// </summary>
        internal static string msgFailToSave
        {
            get
            {
                return ResourceManager.GetString("msgFailToSave", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invalid Customer..
        /// </summary>
        internal static string msgInvalidCustomer
        {
            get
            {
                return ResourceManager.GetString("msgInvalidCustomer", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invalid Email ID.
        /// </summary>
        internal static string msgInvalidEmail
        {
            get
            {
                return ResourceManager.GetString("msgInvalidEmail", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please provide valid values..
        /// </summary>
        internal static string msgInvalidField
        {
            get
            {
                return ResourceManager.GetString("msgInvalidField", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invalid Move.
        /// </summary>
        internal static string msgInvalidMove
        {
            get
            {
                return ResourceManager.GetString("msgInvalidMove", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invalid Phone Number.
        /// </summary>
        internal static string msgInvalidPhoneNumber
        {
            get
            {
                return ResourceManager.GetString("msgInvalidPhoneNumber", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Move does not exists or invalid..
        /// </summary>
        internal static string msgMoveNotExistsOrInvalid
        {
            get
            {
                return ResourceManager.GetString("msgMoveNotExistsOrInvalid", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No data found for given EmailID..
        /// </summary>
        internal static string msgNoDataFoundForEmail
        {
            get
            {
                return ResourceManager.GetString("msgNoDataFoundForEmail", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No data found for this move..
        /// </summary>
        internal static string msgNoDataFoundForMove
        {
            get
            {
                return ResourceManager.GetString("msgNoDataFoundForMove", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No data received to save..
        /// </summary>
        internal static string msgNoDataToSave
        {
            get
            {
                return ResourceManager.GetString("msgNoDataToSave", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No document found for given Move..
        /// </summary>
        internal static string msgNoDocumentFound
        {
            get
            {
                return ResourceManager.GetString("msgNoDocumentFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No valid verification code found..
        /// </summary>
        internal static string msgNoVerificationCodeFound
        {
            get
            {
                return ResourceManager.GetString("msgNoVerificationCodeFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Something went wrong while generating OTP..
        /// </summary>
        internal static string msgOTPGenerationError
        {
            get
            {
                return ResourceManager.GetString("msgOTPGenerationError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Password created successfully..
        /// </summary>
        internal static string msgPasswordCreated
        {
            get
            {
                return ResourceManager.GetString("msgPasswordCreated", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Saved Successfully..
        /// </summary>
        internal static string msgSavedSuccessfully
        {
            get
            {
                return ResourceManager.GetString("msgSavedSuccessfully", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Service Unavailable..
        /// </summary>
        internal static string msgServiceUnavailable
        {
            get
            {
                return ResourceManager.GetString("msgServiceUnavailable", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to CRM Service is unavailable or unauthorized..
        /// </summary>
        internal static string msgServiceUnavailableUnauthorized
        {
            get
            {
                return ResourceManager.GetString("msgServiceUnavailableUnauthorized", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Issue occured while sending email..
        /// </summary>
        internal static string msgUnableToSendEmail
        {
            get
            {
                return ResourceManager.GetString("msgUnableToSendEmail", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Customer is not registered..
        /// </summary>
        internal static string msgUnregisteredCustomer
        {
            get
            {
                return ResourceManager.GetString("msgUnregisteredCustomer", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to sp_UpdateCustomerVerification.
        /// </summary>
        internal static string sp_UpdateCustomerVerification
        {
            get
            {
                return ResourceManager.GetString("sp_UpdateCustomerVerification", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to SQL Connection is closed..
        /// </summary>
        internal static string sqlConnectionClosed
        {
            get
            {
                return ResourceManager.GetString("sqlConnectionClosed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to SQL Connection is opened. .
        /// </summary>
        internal static string sqlConnectionOpened
        {
            get
            {
                return ResourceManager.GetString("sqlConnectionOpened", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to SQL command failed. Exact error received is .
        /// </summary>
        internal static string sqlQueryFailed
        {
            get
            {
                return ResourceManager.GetString("sqlQueryFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to SQL command successfully completed. Exact command text is .
        /// </summary>
        internal static string sqlQuerySuccessful
        {
            get
            {
                return ResourceManager.GetString("sqlQuerySuccessful", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to UPDATE Alerts 
        ///SET {0}
        ///WHERE AlertID = &apos;{1}&apos;.
        /// </summary>
        internal static string updateAlertData
        {
            get
            {
                return ResourceManager.GetString("updateAlertData", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to UPDATE Customers 
        ///SET {0}
        ///WHERE CustomerId = &apos;{1}&apos;.
        /// </summary>
        internal static string updateCustomerData
        {
            get
            {
                return ResourceManager.GetString("updateCustomerData", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Update Customers 
        ///Set EmailID=@EmailID,
        ///	PasswordHash=@PasswordHash,
        ///	PasswordSalt=@PasswordSalt,
        ///	Phone=@Phone,
        ///	LastLoginDate=@LastLogin,
        ///	VerificationCode=@OTP,
        ///	CodeValidTill=@OTPValidTill,
        ///	TermsAgreed=@TermsAgreed,
        ///	PreferredContact=@PreferredContact,
        ///	ReceiveNotifications=@ReceiveNotifications 
        ///where CustomerId=@CustomerId.
        /// </summary>
        internal static string updateCustomerDetails
        {
            get
            {
                return ResourceManager.GetString("updateCustomerDetails", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Update Customers Set PasswordHash=@PasswordHash,
        ///PasswordSalt=@PasswordSalt
        ///where CustomerId=@CustomerId.
        /// </summary>
        internal static string UpdateCustomerVerificationData
        {
            get
            {
                return ResourceManager.GetString("UpdateCustomerVerificationData", resourceCulture);
            }
        }
    }
}
