//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JKMAndroidApp {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JKMAndroidApp.StringResource", typeof(StringResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beginning of Day of Service Check-In.
        /// </summary>
        internal static string AlertBeginningofDayofServiceCheckIn {
            get {
                return ResourceManager.GetString("AlertBeginningofDayofServiceCheckIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BookYourMove.
        /// </summary>
        internal static string AlertBookYourMove {
            get {
                return ResourceManager.GetString("AlertBookYourMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete Wizard Reminder.
        /// </summary>
        internal static string AlertCompleteWizardReminder {
            get {
                return ResourceManager.GetString("AlertCompleteWizardReminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Service Change.
        /// </summary>
        internal static string AlertDateOfServiceChange {
            get {
                return ResourceManager.GetString("AlertDateOfServiceChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End of Service Check-In.
        /// </summary>
        internal static string AlertEndOfServiceCheckIn {
            get {
                return ResourceManager.GetString("AlertEndOfServiceCheckIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final Payment Made.
        /// </summary>
        internal static string AlertPaymentMade {
            get {
                return ResourceManager.GetString("AlertPaymentMade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pre-Move Confirmation.
        /// </summary>
        internal static string AlertPreMoveConfirmation {
            get {
                return ResourceManager.GetString("AlertPreMoveConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00.
        /// </summary>
        internal static string formate00 {
            get {
                return ResourceManager.GetString("formate00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.jkmoving.com/about.
        /// </summary>
        internal static string JKMAboutUsUrl {
            get {
                return ResourceManager.GetString("JKMAboutUsUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CustomerID.
        /// </summary>
        internal static string keyCustomerID {
            get {
                return ResourceManager.GetString("keyCustomerID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InfoScreen.
        /// </summary>
        internal static string keyInfoScreen {
            get {
                return ResourceManager.GetString("keyInfoScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LastLoginDate.
        /// </summary>
        internal static string keyLastLoginDate {
            get {
                return ResourceManager.GetString("keyLastLoginDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/pdf.
        /// </summary>
        internal static string msAapplication_pdf {
            get {
                return ResourceManager.GetString("msAapplication_pdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 000000000.
        /// </summary>
        internal static string msg000000000 {
            get {
                return ResourceManager.GetString("msg000000000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABOUT US.
        /// </summary>
        internal static string msgAbout {
            get {
                return ResourceManager.GetString("msgAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALERTS.
        /// </summary>
        internal static string msgAlert {
            get {
                return ResourceManager.GetString("msgAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert not found..
        /// </summary>
        internal static string msgAlertNotFound {
            get {
                return ResourceManager.GetString("msgAlertNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to exit ?.
        /// </summary>
        internal static string msgApplicationExit {
            get {
                return ResourceManager.GetString("msgApplicationExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot go back, the back button is disabled for this screen..
        /// </summary>
        internal static string msgBackButtonDisable {
            get {
                return ResourceManager.GetString("msgBackButtonDisable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit Payment.
        /// </summary>
        internal static string msgbtnSubmitPayment {
            get {
                return ResourceManager.GetString("msgbtnSubmitPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card number is required..
        /// </summary>
        internal static string msgCardNumberIsRequired {
            get {
                return ResourceManager.GetString("msgCardNumberIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose.
        /// </summary>
        internal static string msgChoose {
            get {
                return ResourceManager.GetString("msgChoose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has some query..
        /// </summary>
        internal static string msgContactusSubject {
            get {
                return ResourceManager.GetString("msgContactusSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost.
        /// </summary>
        internal static string msgCost {
            get {
                return ResourceManager.GetString("msgCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coverage.
        /// </summary>
        internal static string msgCoverage {
            get {
                return ResourceManager.GetString("msgCoverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreatePasswordActivity.
        /// </summary>
        internal static string msgCreatePassword {
            get {
                return ResourceManager.GetString("msgCreatePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CustomerPasswordActivity.
        /// </summary>
        internal static string msgCustomerPassword {
            get {
                return ResourceManager.GetString("msgCustomerPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CVV is required..
        /// </summary>
        internal static string msgCVVIsRequired {
            get {
                return ResourceManager.GetString("msgCVVIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DASHBOARD.
        /// </summary>
        internal static string msgDashboard {
            get {
                return ResourceManager.GetString("msgDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DashBoardActivity.
        /// </summary>
        internal static string msgDashBoardActivity {
            get {
                return ResourceManager.GetString("msgDashBoardActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard does not load..
        /// </summary>
        internal static string msgDashboardNotLoad {
            get {
                return ResourceManager.GetString("msgDashboardNotLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to days ago.
        /// </summary>
        internal static string msgDaysAgo {
            get {
                return ResourceManager.GetString("msgDaysAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DebugTagActivityMain.
        /// </summary>
        internal static string msgDebugTagActivityMain {
            get {
                return ResourceManager.GetString("msgDebugTagActivityMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Declared Value.
        /// </summary>
        internal static string msgDeclaredValue {
            get {
                return ResourceManager.GetString("msgDeclaredValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Spread.
        /// </summary>
        internal static string msgDeliverSpread {
            get {
                return ResourceManager.GetString("msgDeliverSpread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery  Scheduled..
        /// </summary>
        internal static string msgDeliverytobeScheduled {
            get {
                return ResourceManager.GetString("msgDeliverytobeScheduled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination address is required..
        /// </summary>
        internal static string msgDestinationAddressRequired {
            get {
                return ResourceManager.GetString("msgDestinationAddressRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} to {1}.
        /// </summary>
        internal static string msgDispalyDeliverySpread {
            get {
                return ResourceManager.GetString("msgDispalyDeliverySpread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please submit your changes.
        /// </summary>
        internal static string msgDisplayDateValidation {
            get {
                return ResourceManager.GetString("msgDisplayDateValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displaying permission rationale to provide additional context..
        /// </summary>
        internal static string msgDisplayPermission {
            get {
                return ResourceManager.GetString("msgDisplayPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service dates can not be blank.
        /// </summary>
        internal static string msgEditDateValidation {
            get {
                return ResourceManager.GetString("msgEditDateValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to message/rfc822.
        /// </summary>
        internal static string msgEmailMessageType {
            get {
                return ResourceManager.GetString("msgEmailMessageType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;en-US&quot;.
        /// </summary>
        internal static string msgEn_US {
            get {
                return ResourceManager.GetString("msgEn_US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your question..
        /// </summary>
        internal static string msgEnterquestion {
            get {
                return ResourceManager.GetString("msgEnterquestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimate.
        /// </summary>
        internal static string msgEstimate {
            get {
                return ResourceManager.GetString("msgEstimate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimate has been updated sucessfully..
        /// </summary>
        internal static string msgEstimateUpdate {
            get {
                return ResourceManager.GetString("msgEstimateUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiry date is required..
        /// </summary>
        internal static string msgExpDateIsRequired {
            get {
                return ResourceManager.GetString("msgExpDateIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry! The Expiry date that you have entered is invalid..
        /// </summary>
        internal static string msgExpiredateValidation {
            get {
                return ResourceManager.GetString("msgExpiredateValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FromActivity.
        /// </summary>
        internal static string msgFromActvity {
            get {
                return ResourceManager.GetString("msgFromActvity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter full name. .
        /// </summary>
        internal static string msgFullNameRequired {
            get {
                return ResourceManager.GetString("msgFullNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hour ago.
        /// </summary>
        internal static string msgHrsAgo {
            get {
                return ResourceManager.GetString("msgHrsAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introscreen.
        /// </summary>
        internal static string msgIntroScreen {
            get {
                return ResourceManager.GetString("msgIntroScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid card number.
        /// </summary>
        internal static string msgInvalidCard {
            get {
                return ResourceManager.GetString("msgInvalidCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special characters are not allowed in Card Holder&apos;s Name..
        /// </summary>
        internal static string msgInvalidCharacter {
            get {
                return ResourceManager.GetString("msgInvalidCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid  CVV no..
        /// </summary>
        internal static string msgInvalidCVV {
            get {
                return ResourceManager.GetString("msgInvalidCVV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Just Now.
        /// </summary>
        internal static string msgJustNow {
            get {
                return ResourceManager.GetString("msgJustNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load date is required..
        /// </summary>
        internal static string msgLoadDateIsRequire {
            get {
                return ResourceManager.GetString("msgLoadDateIsRequire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to Logout ?.
        /// </summary>
        internal static string msgLogout {
            get {
                return ResourceManager.GetString("msgLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minutes ago.
        /// </summary>
        internal static string msgMinutesAgo {
            get {
                return ResourceManager.GetString("msgMinutesAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery date is required.
        /// </summary>
        internal static string msgMoveDateIsRequire {
            get {
                return ResourceManager.GetString("msgMoveDateIsRequire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MY ACCOUNT.
        /// </summary>
        internal static string msgMyAccount {
            get {
                return ResourceManager.GetString("msgMyAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MY DOCUMENTS.
        /// </summary>
        internal static string msgMyDocuments {
            get {
                return ResourceManager.GetString("msgMyDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MOVE DETAILS.
        /// </summary>
        internal static string msgMyMoveDetails {
            get {
                return ResourceManager.GetString("msgMyMoveDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MY SERVICES.
        /// </summary>
        internal static string msgMyServices {
            get {
                return ResourceManager.GetString("msgMyServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of Cardholder is required..
        /// </summary>
        internal static string msgNameofCardholderisRequired {
            get {
                return ResourceManager.GetString("msgNameofCardholderisRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO.
        /// </summary>
        internal static string msgNo {
            get {
                return ResourceManager.GetString("msgNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No active move for this customer..
        /// </summary>
        internal static string msgNoMoveForCustomer {
            get {
                return ResourceManager.GetString("msgNoMoveForCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You should agree to continue further..
        /// </summary>
        internal static string msgNotAgree {
            get {
                return ResourceManager.GetString("msgNotAgree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your internet connectivity..
        /// </summary>
        internal static string msgNotConnectedInternet {
            get {
                return ResourceManager.GetString("msgNotConnectedInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string msgOK {
            get {
                return ResourceManager.GetString("msgOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Origin address is required..
        /// </summary>
        internal static string msgOriginAddressRequired {
            get {
                return ResourceManager.GetString("msgOriginAddressRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pack date is required..
        /// </summary>
        internal static string msgPackDateIsRequire {
            get {
                return ResourceManager.GetString("msgPackDateIsRequire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pack date must be less than Load date.
        /// </summary>
        internal static string msgPackdatemustbelessthanloaddate {
            get {
                return ResourceManager.GetString("msgPackdatemustbelessthanloaddate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pack date must be less than Delivery date..
        /// </summary>
        internal static string msgPackdatemustbelessthanmovedate {
            get {
                return ResourceManager.GetString("msgPackdatemustbelessthanmovedate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been created sucessfully..
        /// </summary>
        internal static string msgPasswordSuccessfully {
            get {
                return ResourceManager.GetString("msgPasswordSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PAYMENT.
        /// </summary>
        internal static string msgPayment {
            get {
                return ResourceManager.GetString("msgPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You payment was unsuccessful.\r\n     Please try again..
        /// </summary>
        internal static string msgPaymentFailMessage {
            get {
                return ResourceManager.GetString("msgPaymentFailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF VIEWER.pdf.
        /// </summary>
        internal static string msgPdfName {
            get {
                return ResourceManager.GetString("msgPdfName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission has now been granted. Showing preview..
        /// </summary>
        internal static string msgPermissionGranted {
            get {
                return ResourceManager.GetString("msgPermissionGranted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission has NOT been granted..
        /// </summary>
        internal static string msgPermissionNotGranted {
            get {
                return ResourceManager.GetString("msgPermissionNotGranted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission has NOT been granted. Requesting permission..
        /// </summary>
        internal static string msgPermissionNotGrantedRequest {
            get {
                return ResourceManager.GetString("msgPermissionNotGrantedRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone no is required..
        /// </summary>
        internal static string msgPhoneNoIsRequired {
            get {
                return ResourceManager.GetString("msgPhoneNoIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number is not valid..
        /// </summary>
        internal static string msgPhoneNumberInvalid {
            get {
                return ResourceManager.GetString("msgPhoneNumberInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter cost value..
        /// </summary>
        internal static string msgPleaseEnetrCostValue {
            get {
                return ResourceManager.GetString("msgPleaseEnetrCostValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount is required..
        /// </summary>
        internal static string msgPleaseEnterAmount {
            get {
                return ResourceManager.GetString("msgPleaseEnterAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter declared value..
        /// </summary>
        internal static string msgPleaseEnterDeclaredValue {
            get {
                return ResourceManager.GetString("msgPleaseEnterDeclaredValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select an estimate from the list..
        /// </summary>
        internal static string msgPleaseSelectAtleastOneEstimate {
            get {
                return ResourceManager.GetString("msgPleaseSelectAtleastOneEstimate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select deductible amount..
        /// </summary>
        internal static string msgPleaseSelectDeductibleAmount {
            get {
                return ResourceManager.GetString("msgPleaseSelectDeductibleAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load date must be less than or same as Delivery date..
        /// </summary>
        internal static string msgPleaseSelectLoadDateGreaterThanorEqualMoveDate {
            get {
                return ResourceManager.GetString("msgPleaseSelectLoadDateGreaterThanorEqualMoveDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pack date must be greater than Load date..
        /// </summary>
        internal static string msgPleaseSelectPackDateGraterThanLoadDate {
            get {
                return ResourceManager.GetString("msgPleaseSelectPackDateGraterThanLoadDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PrivacyPolicyActivity.
        /// </summary>
        internal static string msgPrivacyPolicyActivity {
            get {
                return ResourceManager.GetString("msgPrivacyPolicyActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your question has been sent successfully..
        /// </summary>
        internal static string msgQuestionSendSuccefully {
            get {
                return ResourceManager.GetString("msgQuestionSendSuccefully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received response for permission request..
        /// </summary>
        internal static string msgRequestPermission {
            get {
                return ResourceManager.GetString("msgRequestPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TERMS .
        /// </summary>
        internal static string msgTerms {
            get {
                return ResourceManager.GetString("msgTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try again.
        /// </summary>
        internal static string msgTryAgain {
            get {
                return ResourceManager.GetString("msgTryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction amount should be less than or equal to TotalDue..
        /// </summary>
        internal static string msgValidAmount {
            get {
                return ResourceManager.GetString("msgValidAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service dates can not be less than or same as current date..
        /// </summary>
        internal static string msgValidDates {
            get {
                return ResourceManager.GetString("msgValidDates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valuation.
        /// </summary>
        internal static string msgValuation {
            get {
                return ResourceManager.GetString("msgValuation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What Matters Most.
        /// </summary>
        internal static string msgWhatMattersMost {
            get {
                return ResourceManager.GetString("msgWhatMattersMost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What matters most is required..
        /// </summary>
        internal static string msgWMMRequired {
            get {
                return ResourceManager.GetString("msgWMMRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YES.
        /// </summary>
        internal static string msgYes {
            get {
                return ResourceManager.GetString("msgYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^(?!0+$)\d{10,}$.
        /// </summary>
        internal static string phoneNumberFormatRegex {
            get {
                return ResourceManager.GetString("phoneNumberFormatRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [^0-9]+.
        /// </summary>
        internal static string phoneNumberStripCharacterRegex {
            get {
                return ResourceManager.GetString("phoneNumberStripCharacterRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to file:///android_asset/privacypolicy.htm.
        /// </summary>
        internal static string PrivacyPolicyUrl {
            get {
                return ResourceManager.GetString("PrivacyPolicyUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ESTIMATES.
        /// </summary>
        internal static string titleEstimate {
            get {
                return ResourceManager.GetString("titleEstimate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to file:///android_asset/Vital InformationHTML.htm.
        /// </summary>
        internal static string VitalInfoURl {
            get {
                return ResourceManager.GetString("VitalInfoURl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acknowledgement.
        /// </summary>
        internal static string wizAcknowledgement {
            get {
                return ResourceManager.GetString("wizAcknowledgement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Addresses.
        /// </summary>
        internal static string wizAddresses {
            get {
                return ResourceManager.GetString("wizAddresses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string wizBtnBack {
            get {
                return ResourceManager.GetString("wizBtnBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string wizBtnCancel {
            get {
                return ResourceManager.GetString("wizBtnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Step.
        /// </summary>
        internal static string wizBtnNextStep {
            get {
                return ResourceManager.GetString("wizBtnNextStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEPOSIT.
        /// </summary>
        internal static string wizDeposit {
            get {
                return ResourceManager.GetString("wizDeposit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimate Review.
        /// </summary>
        internal static string wizEstimadeReview {
            get {
                return ResourceManager.GetString("wizEstimadeReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Confirmed.
        /// </summary>
        internal static string wizMoveConfirmed {
            get {
                return ResourceManager.GetString("wizMoveConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Dates.
        /// </summary>
        internal static string wizServiceDates {
            get {
                return ResourceManager.GetString("wizServiceDates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        internal static string wizServices {
            get {
                return ResourceManager.GetString("wizServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valuation.
        /// </summary>
        internal static string wizValuation {
            get {
                return ResourceManager.GetString("wizValuation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vital Information.
        /// </summary>
        internal static string wizVitalInformation {
            get {
                return ResourceManager.GetString("wizVitalInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What Matters Most.
        /// </summary>
        internal static string wizWhatMattersMost {
            get {
                return ResourceManager.GetString("wizWhatMattersMost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, Captured Correctly.
        /// </summary>
        internal static string wizYesCapturedCorrectly {
            get {
                return ResourceManager.GetString("wizYesCapturedCorrectly", resourceCulture);
            }
        }
    }
}
