//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JKMServices.BLL {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JKMServices.BLL.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 80.
        /// </summary>
        internal static string Address_CityLength {
            get {
                return ResourceManager.GetString("Address_CityLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 80.
        /// </summary>
        internal static string Address_CountryLength {
            get {
                return ResourceManager.GetString("Address_CountryLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 250.
        /// </summary>
        internal static string Address_Line1Length {
            get {
                return ResourceManager.GetString("Address_Line1Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 250.
        /// </summary>
        internal static string Address_Line2Length {
            get {
                return ResourceManager.GetString("Address_Line2Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 50.
        /// </summary>
        internal static string Address_StateLength {
            get {
                return ResourceManager.GetString("Address_StateLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20.
        /// </summary>
        internal static string Address_ZipCodeLength {
            get {
                return ResourceManager.GetString("Address_ZipCodeLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRM connection is lost..
        /// </summary>
        internal static string CRM_ConnectionLost {
            get {
                return ResourceManager.GetString("CRM_ConnectionLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string crm_contact_phoneNumber {
            get {
                return ResourceManager.GetString("crm_contact_phoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100000001.
        /// </summary>
        internal static string crm_jkmoving_01 {
            get {
                return ResourceManager.GetString("crm_jkmoving_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100000002.
        /// </summary>
        internal static string crm_jkmoving_1001 {
            get {
                return ResourceManager.GetString("crm_jkmoving_1001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100000003.
        /// </summary>
        internal static string crm_jkmoving_2501 {
            get {
                return ResourceManager.GetString("crm_jkmoving_2501", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100000004.
        /// </summary>
        internal static string crm_jkmoving_5001 {
            get {
                return ResourceManager.GetString("crm_jkmoving_5001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100000000.
        /// </summary>
        internal static string crm_jkmoving_minimum1 {
            get {
                return ResourceManager.GetString("crm_jkmoving_minimum1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 676860001.
        /// </summary>
        internal static string crm_onerivet_0 {
            get {
                return ResourceManager.GetString("crm_onerivet_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 676860002.
        /// </summary>
        internal static string crm_onerivet_100 {
            get {
                return ResourceManager.GetString("crm_onerivet_100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 676860003.
        /// </summary>
        internal static string crm_onerivet_250 {
            get {
                return ResourceManager.GetString("crm_onerivet_250", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 676860004.
        /// </summary>
        internal static string crm_onerivet_500 {
            get {
                return ResourceManager.GetString("crm_onerivet_500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 676860000.
        /// </summary>
        internal static string crm_onerivet_minimum {
            get {
                return ResourceManager.GetString("crm_onerivet_minimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 204 - NoContent.
        /// </summary>
        internal static string CRM_STATUS_204 {
            get {
                return ResourceManager.GetString("CRM_STATUS_204", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {}.
        /// </summary>
        internal static string emptyJson {
            get {
                return ResourceManager.GetString("emptyJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Origin and Destination addresses fields cannot be empty..
        /// </summary>
        internal static string logAddressFieldsCannotEmpty {
            get {
                return ResourceManager.GetString("logAddressFieldsCannotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured while date conversion..
        /// </summary>
        internal static string logDateConversionError {
            get {
                return ResourceManager.GetString("logDateConversionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date fields cannot be empty..
        /// </summary>
        internal static string logDateFieldsCannotEmpty {
            get {
                return ResourceManager.GetString("logDateFieldsCannotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid request content..
        /// </summary>
        internal static string logInvalidRequestContent {
            get {
                return ResourceManager.GetString("logInvalidRequestContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method Encountered.
        /// </summary>
        internal static string logMethodEncountered {
            get {
                return ResourceManager.GetString("logMethodEncountered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valuation fields cannot be empty..
        /// </summary>
        internal static string logValuationFieldsCannotEmpty {
            get {
                return ResourceManager.GetString("logValuationFieldsCannotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad Request.
        /// </summary>
        internal static string msgBadRequest {
            get {
                return ResourceManager.GetString("msgBadRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please contact move co-ordinator.
        /// </summary>
        internal static string msgContactMoveCoordinator {
            get {
                return ResourceManager.GetString("msgContactMoveCoordinator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CustomerID is successfully retrieved..
        /// </summary>
        internal static string msgCustomerIdRetrieved {
            get {
                return ResourceManager.GetString("msgCustomerIdRetrieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer does not exists or invalid..
        /// </summary>
        internal static string msgCustomerNotExistsOrInvalid {
            get {
                return ResourceManager.GetString("msgCustomerNotExistsOrInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document does not exists..
        /// </summary>
        internal static string msgDocumentDoesNotExists {
            get {
                return ResourceManager.GetString("msgDocumentDoesNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured while inserting new alert:.
        /// </summary>
        internal static string msgErrorInInsertingNewAlert {
            get {
                return ResourceManager.GetString("msgErrorInInsertingNewAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured in verification process..
        /// </summary>
        internal static string msgErrorInVerificationProcess {
            get {
                return ResourceManager.GetString("msgErrorInVerificationProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue occured while getting Alert list.
        /// </summary>
        internal static string msgErrorOccuredInGettingAlertList {
            get {
                return ResourceManager.GetString("msgErrorOccuredInGettingAlertList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue occured while retrieving Customer detail..
        /// </summary>
        internal static string msgErrorOccuredInGettingCustomerID {
            get {
                return ResourceManager.GetString("msgErrorOccuredInGettingCustomerID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured while assigning request content to DTO..
        /// </summary>
        internal static string msgErrorOccuredWhileAssigningDTO {
            get {
                return ResourceManager.GetString("msgErrorOccuredWhileAssigningDTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save the details..
        /// </summary>
        internal static string msgFailToSave {
            get {
                return ResourceManager.GetString("msgFailToSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Customer..
        /// </summary>
        internal static string msgInvalidCustomer {
            get {
                return ResourceManager.GetString("msgInvalidCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Email ID.
        /// </summary>
        internal static string msgInvalidEmail {
            get {
                return ResourceManager.GetString("msgInvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide valid values..
        /// </summary>
        internal static string msgInvalidField {
            get {
                return ResourceManager.GetString("msgInvalidField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Move.
        /// </summary>
        internal static string msgInvalidMove {
            get {
                return ResourceManager.GetString("msgInvalidMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No alerts found..
        /// </summary>
        internal static string msgNoAlertFound {
            get {
                return ResourceManager.GetString("msgNoAlertFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data found for given EmailID..
        /// </summary>
        internal static string msgNoDataFoundForEmail {
            get {
                return ResourceManager.GetString("msgNoDataFoundForEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data found for this move..
        /// </summary>
        internal static string msgNoDataFoundForMove {
            get {
                return ResourceManager.GetString("msgNoDataFoundForMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data received to save..
        /// </summary>
        internal static string msgNoDataToSave {
            get {
                return ResourceManager.GetString("msgNoDataToSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No document found for given Move..
        /// </summary>
        internal static string msgNoDocumentFound {
            get {
                return ResourceManager.GetString("msgNoDocumentFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No estimate exist for customer..
        /// </summary>
        internal static string msgNoEstimateExistsForCustomer {
            get {
                return ResourceManager.GetString("msgNoEstimateExistsForCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No match found..
        /// </summary>
        internal static string msgNoMatchFound {
            get {
                return ResourceManager.GetString("msgNoMatchFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong while generating OTP..
        /// </summary>
        internal static string msgOTPGenerationError {
            get {
                return ResourceManager.GetString("msgOTPGenerationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password created successfully..
        /// </summary>
        internal static string msgPasswordCreated {
            get {
                return ResourceManager.GetString("msgPasswordCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request content created successfully..
        /// </summary>
        internal static string msgRequestContentCreated {
            get {
                return ResourceManager.GetString("msgRequestContentCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved Successfully..
        /// </summary>
        internal static string msgSavedSuccessfully {
            get {
                return ResourceManager.GetString("msgSavedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Unavailable..
        /// </summary>
        internal static string msgServiceUnavailable {
            get {
                return ResourceManager.GetString("msgServiceUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL connection lost..
        /// </summary>
        internal static string msgSQLConnectionLost {
            get {
                return ResourceManager.GetString("msgSQLConnectionLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue occured while sending email..
        /// </summary>
        internal static string msgUnableToSendEmail {
            get {
                return ResourceManager.GetString("msgUnableToSendEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to send email to move co-ordinator..
        /// </summary>
        internal static string msgUnableToSendEmailToMoveCoordinator {
            get {
                return ResourceManager.GetString("msgUnableToSendEmailToMoveCoordinator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer is not registered..
        /// </summary>
        internal static string msgUnregisteredCustomer {
            get {
                return ResourceManager.GetString("msgUnregisteredCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request content validation failed..
        /// </summary>
        internal static string msgValidateRequestContentFail {
            get {
                return ResourceManager.GetString("msgValidateRequestContentFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request content validated successfully..
        /// </summary>
        internal static string msgValidateRequestContentSuccess {
            get {
                return ResourceManager.GetString("msgValidateRequestContentSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        internal static string PreferredContactMethodCode_Email {
            get {
                return ResourceManager.GetString("PreferredContactMethodCode_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        internal static string PreferredContactMethodCode_Phone {
            get {
                return ResourceManager.GetString("PreferredContactMethodCode_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 148050000.
        /// </summary>
        internal static string StatusCodeNeedsOverride {
            get {
                return ResourceManager.GetString("StatusCodeNeedsOverride", resourceCulture);
            }
        }
    }
}
