// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace JKMIOSApp
{
	public partial class EmailLViewController : UIViewController
	{
		public EmailLViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
