// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using JKMPCL.Model;
using JKMPCL.Services;
using UIKit;

namespace JKMIOSApp
{
	public partial class estimateListTableCell : UITableViewCell
	{
        public EstimateModel estimateModel { get; set; }
        public UITableView tableView { get; set; }
        private EstimateListViewController estimateListViewController { get; set; }


		public estimateListTableCell (IntPtr handle) : base (handle)
		{
		}
        public override void AwakeFromNib()
        {
            btnSelectEstimate.TouchUpInside += BtnSelectEstimate_TouchUpInside;
        }
        /// <summary>
        /// Method Name     : BtnSelectEstimate_TouchUpInside
        /// Author          : Hiren Patel
        /// Creation Date   : 25 Jan 2018
        /// Purpose         : Click to select estimate
        /// Revision        : 
        /// </summary>
        /// <param name="e">Event Argument</param>
        private void BtnSelectEstimate_TouchUpInside(object sender, EventArgs e)
        {
            btnSelectEstimate.SetImage(UIImage.FromFile(AppConstant.ESTIMATE_SELECETD_IMAGE_URL), UIControlState.Normal);
            UtilityPCL.selectedMoveNumber = lblEstimateTitle.Text;
            tableView.ReloadData();
        }

        /// <summary>
        /// Method Name     : SetEstimateData
        /// Author          : Hiren Patel
        /// Creation Date   : 30 Dec 2017
        /// Purpose         : Set estimates data
        /// Revision        : 
        /// </summary>
        public void SetEstimateData( EstimateModel estimateModel,UITableView tableView, EstimateListViewController estimateListViewController)
        {
            this.estimateListViewController = estimateListViewController;
            this.estimateModel = estimateModel;
            lblEstimateTitle.Text = estimateModel.MoveNumber;
            if (string.IsNullOrEmpty(estimateModel.EstimatedLineHaul))
            {
                lblExcessValuation.Text = UtilityPCL.CurrencyFormat("0");
            }
            else
            {
                lblExcessValuation.Text = estimateModel.EstimatedLineHaul;
            }

            if (estimateModel.MoveNumber == UtilityPCL.selectedMoveNumber)
            {
                btnSelectEstimate.SetImage(UIImage.FromFile(AppConstant.ESTIMATE_SELECETD_IMAGE_URL), UIControlState.Normal);
            }
            else
            {
                btnSelectEstimate.SetImage(UIImage.FromFile(AppConstant.ESTIMATE_UNSELECETD_IMAGE_URL), UIControlState.Normal);
            }

            SetIimgViewEstimateTap();
            btnSelectEstimate.TintColor = UIColor.White;
            btnSelectEstimate.Layer.BorderWidth = 0;
            this.tableView = tableView; 
        }

        /// <summary>
        /// Method Name     : SetTapEventToLoadDateTextBox
        /// Author          : Hiren Patel
        /// Creation Date   : 31 Jan 2017
        /// Purpose         : Sets the tap event to load date text box.
        /// Revision        : 
        /// </summary>
        private void SetIimgViewEstimateTap()
        {
            imgViewEstimate.UserInteractionEnabled = true;
            UITapGestureRecognizer imgViewEstimateTap = new UITapGestureRecognizer(() =>
            {
                if (estimateListViewController != null)
                {
                    UtilityPCL.selectedMoveNumber = lblEstimateTitle.Text;
                    UIHelper.CallingScreen = JKMEnum.UIViewControllerID.EstimateListView;
                    UIHelper.RedirectToViewController(estimateListViewController, JKMEnum.UIViewControllerID.ViewEstimateReviewView);
                }
            });
            imgViewEstimate.AddGestureRecognizer(imgViewEstimateTap);

        }
	}
}
