// This file has been autogenerated from a class added in the UI designer.

using System;
using UIKit;

namespace JKMIOSApp
{
    /// <summary>
    /// Controller Name : JKTabController
    /// Author          : Hiren Patel
    /// Creation Date   : 2 JAN 2018
    /// Purpose         : To display parent screen as dashboard and other app shell screen 
    /// Revision        : 
    /// </summary>
    public partial class JKTabController : UITabBarController
    {
        public JKTabController(IntPtr handle) : base(handle)
        {
        }
        public override void ViewDidLoad()
        {
            base.ViewDidLoad();
        }

        public override void ViewDidAppear(bool animated)
        {
            base.ViewDidAppear(animated);
            SetTabBarProperty();


        }

        /// <summary>
        /// Method Name     : CallGetContactMoveService
        /// Author          : Hiren Patel
        /// Creation Date   : 5 Jan 2018
        /// Purpose         : Sets the tab bar property.
        /// Revision        : 
        /// </summary>
        public void SetTabBarProperty()
        {
            if (TabBar.Items != null && ( UIHelper.ScreenSize(View) == AppConstant.IPHONE_4_WIDTH_AND_HEIGHT || UIHelper.ScreenSize(View) == AppConstant.IPHONE_5_WIDTH_AND_HEIGHT))
            {
                 var items = TabBar.Items;
                    foreach (var tabBar in items)
                    {
                        var txtSelectedColor = new UITextAttributes()
                        {
                            TextColor = UIColor.Orange
                        };

                        var txtFont = new UITextAttributes()
                        {
                            Font = UIFont.SystemFontOfSize(8)
                        };

                       tabBar.SetTitleTextAttributes(txtSelectedColor, UIControlState.Normal);
                       tabBar.SetTitleTextAttributes(txtFont, UIControlState.Normal);

                }
            }
        }
    }

}
