// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using JKMPCL.Common;
using JKMPCL.Model;
using JKMPCL.Services;
using UIKit;

namespace JKMIOSApp
{
    /// <summary>
    /// Controller Name : MoveDetailsViewController
    /// Author          : Hiren Patel
    /// Creation Date   : 16 JAN 2018
    /// Purpose         : To display move details
    /// Revision        : 
    /// </summary>
	public partial class MoveDetailsViewController : UIViewController
	{
        
		public MoveDetailsViewController (IntPtr handle) : base (handle)
		{
		}

        public override void ViewWillAppear(bool animated)
        {
            base.ViewWillAppear(animated);
        }

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();
            InitilizeIntarface();
            PopulateData();
        }

        /// <summary>
        /// Method Name     : InitilizeIntarface
        /// Author          : Hiren Patel
        /// Creation Date   : 29 Dec 2017
        /// Purpose         : To Initilizes the intarface.
        /// Revision        : 
        /// </summary>
        public void InitilizeIntarface()
        {
            // InitilizeIntarface
            UIHelper.SetDefaultWizardScrollViewBorderProperty(scrollViewPackDate);
            UIHelper.SetDefaultWizardScrollViewBorderProperty(scrollViewLoadDate);
            UIHelper.SetDefaultWizardScrollViewBorderProperty(scrollViewDeliveryDate);

            btnAlert.TouchUpInside += BtnAlert_TouchUpInside;
            btnContactUs.TouchUpInside += BtnContactUs_TouchUpInside;

            lblLoadDate.Text = string.Empty;
            lblPackDate.Text = string.Empty;
            lblDeliveryDate.Text = string.Empty;

        }

        public override void ViewDidAppear(bool animated)
        {
            base.ViewDidAppear(animated);
        }

        /// <summary>
        /// Event Name      : BtnContactUs_TouchUpInside
        /// Author          : Hiren Patel
        /// Creation Date   : 2 Dec 2017
        /// Purpose         : To redirect contactus page
        /// Revision        : 
        /// </summary>
        /// <param name="sender">Sender.</param>
        /// <param name="e">Event Argument</param>
        private void BtnContactUs_TouchUpInside(object sender, EventArgs e)
        {
            PerformSegue("moveDetailsToDashboard", this);
        }

        /// <summary>
        /// Event Name      : BtnAlert_TouchUpInside
        /// Author          : Hiren Patel
        /// Creation Date   : 2 Dec 2017
        /// Purpose         : To redirect notification
        /// Revision        : 
        /// </summary>
        /// <param name="sender">Sender.</param>
        /// <param name="e">Event Argument</param>
        private void BtnAlert_TouchUpInside(object sender, EventArgs e)
        {
            PerformSegue("movedetailsToAlertList", this);
        }

        /// <summary>
        /// Event Name      : BtnAlert_TouchUpInside
        /// Author          : Hiren Patel
        /// Creation Date   : 2 Dec 2017
        /// Purpose         : Populates the move details data.
        /// Revision        : 
        /// </summary>
        public void  PopulateData()
        {
            if (DTOConsumer.dtoMoveData != null)
            {
                MoveDataModel dtoMoveData = DTOConsumer.dtoMoveData;
                lblPackDate.Text = dtoMoveData.MoveDetails_PackStartDate;
                lblLoadDate.Text = dtoMoveData.MoveDetails_LoadStartDate;
                if(!UtilityPCL.IsNullOrEmptyOrWhiteSpace(dtoMoveData.MoveDetails_DeliveryStartDate) && !UtilityPCL.IsNullOrEmptyOrWhiteSpace(dtoMoveData.MoveDetails_DeliveryEndDate) )
                {
                    if(dtoMoveData.MoveDetails_DeliveryStartDate == dtoMoveData.MoveDetails_DeliveryEndDate)
                    {
                        lblDeliveryDate.Text = dtoMoveData.MoveDetails_DeliveryStartDate;
                    }
                    else
                    {
                        SetDeliverySpreadData(dtoMoveData.MoveDetails_DeliveryStartDate, dtoMoveData.MoveDetails_DeliveryEndDate);
                    }
                }
            }
        }

        /// <summary>
        /// Event Name      : BtnAlert_TouchUpInside
        /// Author          : Hiren Patel
        /// Creation Date   : 2 Dec 2017
        /// Purpose         : Sets the delivery spread data.
        /// Revision        : 
        /// </summary>
        /// <param name="deliveryStartDate">Delivery start date.</param>
        /// <param name="DeliveryEndDate">Delivery end date.</param>
        public void SetDeliverySpreadData(string deliveryStartDate,string DeliveryEndDate)
        {
            lblDeliveryDateTitle.Text = "Delivery Spread";
            lblDeliveryDate.Text = string.Format("{0} to {1}", deliveryStartDate,DeliveryEndDate);
            imgDeliveryDate.Image = UIImage.FromFile("delivery.png");
            imgArrowDeliveryDate.Image = UIImage.FromFile("arrow-gold.png");
        }

	}
}
