// This file has been autogenerated from a class added in the UI designer.

using System;
using CoreGraphics;
using Foundation;
using JKMPCL.Services;
using UIKit;

namespace JKMIOSApp
{
    /// <summary>
    /// Controller Name : MyMoreViewController
    /// Author          : Hiren Patel
    /// Creation Date   : 16 JAN 2018
    /// Purpose         : To display more view page screen as app shell screen
    /// Revision        : 
    /// </summary>
	public partial class MyMoreViewController : UIViewController
    {
        CGRect originalLocation;
        CGRect resetLocation;
        JKTabController parent;
        public MyMoreViewController(IntPtr handle) : base(handle)
        {
        }
        public override void ViewDidLoad()
        {
            base.ViewDidLoad();
            InitilizeIntarface();

            NavigationItem.Title = "More";
            CGSize temp1 = new CGSize(MenuView.Frame.Width, MenuView.Frame.Height);
            CGPoint temp = new CGPoint(scrollviewOption.Frame.Width - 180, scrollviewOption.Frame.Height - (MenuView.Frame.Height + 55));
            originalLocation = new CGRect(temp, temp1);

            temp1 = new CGSize(MenuView.Frame.Width, MenuView.Frame.Height);
            temp = new CGPoint(scrollviewOption.Frame.Width - 180, scrollviewOption.Frame.Height);
            resetLocation = new CGRect(temp, temp1);

            if (this.ParentViewController != null)
            {
                parent = this.ParentViewController as JKTabController;
                scrollviewOption.Frame = parent.View.Frame;
                parent.View.Add(scrollviewOption);
            }

        }
        /// <summary>
        /// Method Name     : InitilizeIntarface
        /// Author          : Hiren Patel
        /// Creation Date   : 29 Dec 2017
        /// Purpose         : To Initilizes the intarface.
        /// Revision        : 
        /// </summary>
        public void InitilizeIntarface()
        {
            // InitilizeIntarface
            btnClose.TouchUpInside += BtnOptionPressed_TouchUpInside;
            btnAboutUS.TouchUpInside += BtnOptionPressed_TouchUpInside;
            btnTerms.TouchUpInside += BtnOptionPressed_TouchUpInside;
            btnMoveDetails.TouchUpInside += BtnOptionPressed_TouchUpInside;
        }

        public override void ViewWillAppear(bool animated)
        {
            base.ViewWillAppear(animated);
            NavigationController.NavigationBarHidden = true;
        }
        public override void ViewDidAppear(bool animated)
        {
            base.ViewDidAppear(animated);
            showScrollviewOption();
        }

        /// <summary>
        /// Method Name     : BtnOptionPressed
        /// Author          : Hiren Patel
        /// Creation Date   : 29 Dec 2017
        /// Purpose         : Buttons the option pressed.
        /// Revision        : 
        /// <summary>
        /// <param name="sender">Sender.</param>
        /// <param name="e">Event Argument</param>
        private void BtnOptionPressed_TouchUpInside(object sender, EventArgs e)
        {
            UIButton button = sender as UIButton;
            var tag = button.Tag;
            switch (tag)
            {
                case 4: //Move Details
                    PerformSegue("menuMoreToMoveDetails", this);
                    break;
                case 3: //Terms
                    PerformSegue("menuMoreToTerms", this);
                    break;
                case 2: //About us
                    using (var encoded = new NSString(string.Format("{0}", AppConstant.ABOUT_US_URL)))
                    using (var url = NSUrl.FromString(encoded))
                    {
                        if (url != null)
                        {
                            UIApplication.SharedApplication.OpenUrl(url);
                        }
                        else
                        {
                            PerformSegue("menumoreToAboutUs", this);
                        }
                    }
                    break;
                case 1: //close
                    PerformSegue("menuMoreToDashboard", this);
                    hideScrollviewOption();

                    break;
            }
        }

        /// <summary>
        /// Method Name     : hideScrollviewOption
        /// Author          : Hiren Patel
        /// Creation Date   : 29 Dec 2017
        /// Purpose         : Hides the scrollview option.
        /// Revision        : 
        /// </summary>
        public void hideScrollviewOption()
        {
            UIView.Animate(0.4f, () =>
            {
                scrollviewOption.Hidden = true;
                AnimateHideButtonView();
            }, () => { });

        }

        /// <summary>
        /// Method Name     : showScrollviewOption
        /// Author          : Hiren Patel
        /// Creation Date   : 29 Dec 2017
        /// Purpose         : Shows the scrollview option.
        /// Revision        : 
        /// </summary>
        private void showScrollviewOption()
        {
            UIView.Animate(0.4f, () =>
            {
                scrollviewOption.Hidden = false;
                AnimateShowButtonView();
            }, () => { });
        }

        /// <summary>
        /// Method Name     : AnimateShowButtonView
        /// Author          : Hiren Patel
        /// Creation Date   : 29 Dec 2017
        /// Purpose         : Animates the show button view.
        /// Revision        : 
        /// </summary>
        private void AnimateShowButtonView()
        {
            MenuView.Frame = originalLocation;
        }

        /// <summary>
        /// Method Name     : showScrollviewOption
        /// Author          : Hiren Patel
        /// Creation Date   : 29 Dec 2017
        /// Purpose         : Animates the hide button view.
        /// Revision        : 
        /// </summary>
        private void AnimateHideButtonView()
        {
            MenuView.Frame = resetLocation;
        }

        public override void ViewWillDisappear(bool animated)
        {
            hideScrollviewOption();
        }

    }
}
