// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using JKMPCL.Common;
using JKMPCL.Model;
using UIKit;

namespace JKMIOSApp
{
    public partial class ViewEstimateController : UIViewController
    {
        private EstimateModel estimateModel;

        public ViewEstimateController(IntPtr handle) : base(handle)
        {
        }

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();
            InitilizeIntarface();
            PopulateData();
        }

        public override void ViewWillAppear(bool animated)
        {
            base.ViewWillAppear(animated);
        }

        public override void ViewDidAppear(bool animated)
        {
            base.ViewDidAppear(animated);
            btnBack.TouchUpInside += BtnBack_TouchUpInside;
        }

        /// <summary>
        /// Method Name     : InitilizeIntarface
        /// Author          : Hiren Patel
        /// Creation Date   : 29 Dec 2017
        /// Purpose         : To Initilizes the intarface.
        /// Revision        : 
        /// </summary>
        public void InitilizeIntarface()
        {

            UIHelper.SetDefaultWizardScrollViewBorderProperty(scrollviewPDFContainer);
        }

        /// <summary>
        /// Event Name      : BtnBack_TouchUpInside
        /// Author          : Hiren Patel
        /// Creation Date   : 29 Dec 2017
        /// Purpose         : To redirec to back screen
        /// Revision        : 
        /// </summary>
        /// <param name="sender">Sender.</param>
        /// <param name="e">Event Argument</param>
        private void BtnBack_TouchUpInside(object sender, EventArgs e)
        {
            if (NavigationController != null)
            {
                DismissViewControllerAsync(true);
            }
            else
            {
                UIHelper.RedirectToViewController(this, UIHelper.CallingScreen);
            }
        }

        /// <summary>
        /// Method Name     : PopulateData
        /// Author          : Hiren Patel
        /// Creation Date   : 2 Dec 2017
        /// Purpose         : fill Estimate Data  
        /// Revision        : 
        /// </summary>
        public void PopulateData()
        {
            uiWebViewPDF.LoadRequest(new NSUrlRequest(new NSUrl(AppConstant.VIEW_ESTIMATE_URL, true)));
            uiWebViewPDF.ScalesPageToFit = true;

            estimateModel = DTOConsumer.GetSelectedEstimate();
            if (estimateModel != null)
            {
                lblEstimateName.Text = estimateModel.MoveNumber;
            }
        }
    }
}
