//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JKMPCL {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MoveDataDisplayResource {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MoveDataDisplayResource() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("JKMPCL.MoveDataDisplayResource", typeof(MoveDataDisplayResource).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string MoveCode_BoxDeliver {
            get {
                return ResourceManager.GetString("MoveCode_BoxDeliver", resourceCulture);
            }
        }
        
        internal static string MoveCode_Export {
            get {
                return ResourceManager.GetString("MoveCode_Export", resourceCulture);
            }
        }
        
        internal static string MoveCode_Imaport {
            get {
                return ResourceManager.GetString("MoveCode_Imaport", resourceCulture);
            }
        }
        
        internal static string MoveCode_Load {
            get {
                return ResourceManager.GetString("MoveCode_Load", resourceCulture);
            }
        }
        
        internal static string MoveCode_Pack {
            get {
                return ResourceManager.GetString("MoveCode_Pack", resourceCulture);
            }
        }
        
        internal static string MoveCode_Release {
            get {
                return ResourceManager.GetString("MoveCode_Release", resourceCulture);
            }
        }
        
        internal static string MoveCode_UnPack {
            get {
                return ResourceManager.GetString("MoveCode_UnPack", resourceCulture);
            }
        }
        
        internal static string MoveCode_Deliver {
            get {
                return ResourceManager.GetString("MoveCode_Deliver", resourceCulture);
            }
        }
        
        internal static string MoveCode_APUFloar {
            get {
                return ResourceManager.GetString("MoveCode_APUFloar", resourceCulture);
            }
        }
        
        internal static string MoveCode_Trailor {
            get {
                return ResourceManager.GetString("MoveCode_Trailor", resourceCulture);
            }
        }
        
        internal static string MoveCode100000000 {
            get {
                return ResourceManager.GetString("MoveCode100000000", resourceCulture);
            }
        }
        
        internal static string MoveCode100000001 {
            get {
                return ResourceManager.GetString("MoveCode100000001", resourceCulture);
            }
        }
        
        internal static string MoveCode100000002 {
            get {
                return ResourceManager.GetString("MoveCode100000002", resourceCulture);
            }
        }
        
        internal static string MoveCode100000003 {
            get {
                return ResourceManager.GetString("MoveCode100000003", resourceCulture);
            }
        }
        
        internal static string MoveCode100000004 {
            get {
                return ResourceManager.GetString("MoveCode100000004", resourceCulture);
            }
        }
        
        internal static string MoveCode100000005 {
            get {
                return ResourceManager.GetString("MoveCode100000005", resourceCulture);
            }
        }
        
        internal static string MoveCode100000006 {
            get {
                return ResourceManager.GetString("MoveCode100000006", resourceCulture);
            }
        }
        
        internal static string MoveCode676860000 {
            get {
                return ResourceManager.GetString("MoveCode676860000", resourceCulture);
            }
        }
        
        internal static string msgMoveCode {
            get {
                return ResourceManager.GetString("msgMoveCode", resourceCulture);
            }
        }
        
        internal static string msgValuationDeductible {
            get {
                return ResourceManager.GetString("msgValuationDeductible", resourceCulture);
            }
        }
        
        internal static string ValuationDeductible10000000 {
            get {
                return ResourceManager.GetString("ValuationDeductible10000000", resourceCulture);
            }
        }
        
        internal static string ValuationDeductible100000001 {
            get {
                return ResourceManager.GetString("ValuationDeductible100000001", resourceCulture);
            }
        }
        
        internal static string ValuationDeductible100000002 {
            get {
                return ResourceManager.GetString("ValuationDeductible100000002", resourceCulture);
            }
        }
        
        internal static string ValuationDeductible100000003 {
            get {
                return ResourceManager.GetString("ValuationDeductible100000003", resourceCulture);
            }
        }
        
        internal static string ValuationDeductible100000004 {
            get {
                return ResourceManager.GetString("ValuationDeductible100000004", resourceCulture);
            }
        }
        
        internal static string msgPending {
            get {
                return ResourceManager.GetString("msgPending", resourceCulture);
            }
        }
        
        internal static string MoveActiveCodeStatus {
            get {
                return ResourceManager.GetString("MoveActiveCodeStatus", resourceCulture);
            }
        }
        
        internal static string msgSelectdeDuctible {
            get {
                return ResourceManager.GetString("msgSelectdeDuctible", resourceCulture);
            }
        }
        
        internal static string Deductible10000000 {
            get {
                return ResourceManager.GetString("Deductible10000000", resourceCulture);
            }
        }
        
        internal static string Deductible100000001 {
            get {
                return ResourceManager.GetString("Deductible100000001", resourceCulture);
            }
        }
        
        internal static string Deductible100000002 {
            get {
                return ResourceManager.GetString("Deductible100000002", resourceCulture);
            }
        }
        
        internal static string Deductible100000003 {
            get {
                return ResourceManager.GetString("Deductible100000003", resourceCulture);
            }
        }
        
        internal static string Deductible100000004 {
            get {
                return ResourceManager.GetString("Deductible100000004", resourceCulture);
            }
        }
        
        internal static string MoveCode148050000 {
            get {
                return ResourceManager.GetString("MoveCode148050000", resourceCulture);
            }
        }
        
        internal static string msgNeedsOverride {
            get {
                return ResourceManager.GetString("msgNeedsOverride", resourceCulture);
            }
        }
    }
}
