//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JKMPCL {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JKMPCL.Resource", typeof(Resource).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert.svc/.
        /// </summary>
        internal static string AlertService {
            get {
                return ResourceManager.GetString("AlertService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to admin.
        /// </summary>
        internal static string ApiAuthenticationPassword {
            get {
                return ResourceManager.GetString("ApiAuthenticationPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to admin.
        /// </summary>
        internal static string ApiAuthenticationUserName {
            get {
                return ResourceManager.GetString("ApiAuthenticationUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://13.92.188.152:88/.
        /// </summary>
        internal static string BaseAPIUrl {
            get {
                return ResourceManager.GetString("BaseAPIUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to johnsmith@gmail.com.
        /// </summary>
        internal static string contactUsDefaultEmailId {
            get {
                return ResourceManager.GetString("contactUsDefaultEmailId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (170) 687-8250.
        /// </summary>
        internal static string contactUsDefaultPhoneNo {
            get {
                return ResourceManager.GetString("contactUsDefaultPhoneNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^(?:4[0-9]{12}(?:[0-9]{3})?|5[1-5][0-9]{14}|6(?:011|5[0-9][0-9])[0-9]{12}|3[47][0-9]{13}|3(?:0[0-5]|[68][0-9])[0-9]{11}|(?:2131|1800|35\d{3})\d{11})$.
        /// </summary>
        internal static string CreditCardValidationRegex {
            get {
                return ResourceManager.GetString("CreditCardValidationRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}{1}/Profile.
        /// </summary>
        internal static string CustomerProfileUrl {
            get {
                return ResourceManager.GetString("CustomerProfileUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.svc/.
        /// </summary>
        internal static string CustomerService {
            get {
                return ResourceManager.GetString("CustomerService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}{1}/verification.
        /// </summary>
        internal static string CustomerVerificationUrl {
            get {
                return ResourceManager.GetString("CustomerVerificationUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Replacement – $0 Deductible..
        /// </summary>
        internal static string D0 {
            get {
                return ResourceManager.GetString("D0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Replacement – $100 Deductible.
        /// </summary>
        internal static string D100 {
            get {
                return ResourceManager.GetString("D100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Replacement – $250 Deductible.
        /// </summary>
        internal static string D250 {
            get {
                return ResourceManager.GetString("D250", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Replacement – $500 Deductible..
        /// </summary>
        internal static string D500 {
            get {
                return ResourceManager.GetString("D500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard – $.60/Lbs..
        /// </summary>
        internal static string D60 {
            get {
                return ResourceManager.GetString("D60", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TBD.
        /// </summary>
        internal static string DateTBD {
            get {
                return ResourceManager.GetString("DateTBD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment.svc/deviceid.
        /// </summary>
        internal static string DeviceIDService {
            get {
                return ResourceManager.GetString("DeviceIDService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document.svc.
        /// </summary>
        internal static string DocumentService {
            get {
                return ResourceManager.GetString("DocumentService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^([\w\.\-]+)@([\w\-]+)((\.(\w){2,3})+)$.
        /// </summary>
        internal static string EmailRegex {
            get {
                return ResourceManager.GetString("EmailRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimate.svc/.
        /// </summary>
        internal static string EstimateService {
            get {
                return ResourceManager.GetString("EstimateService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment.svc/{0}/amount.
        /// </summary>
        internal static string GetAmountServiceUrl {
            get {
                return ResourceManager.GetString("GetAmountServiceUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^(51|52|53|54|55).
        /// </summary>
        internal static string MasterCardTypeRegex {
            get {
                return ResourceManager.GetString("MasterCardTypeRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MM-dd-yyyy.
        /// </summary>
        internal static string MM_dd_yyyyDateFormat {
            get {
                return ResourceManager.GetString("MM_dd_yyyyDateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MM/dd/yyyy.
        /// </summary>
        internal static string MMddyyyyDateFormat {
            get {
                return ResourceManager.GetString("MMddyyyyDateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}{1}/contact.
        /// </summary>
        internal static string MoveContactUrl {
            get {
                return ResourceManager.GetString("MoveContactUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}{1}/Move.
        /// </summary>
        internal static string MoveIDUrl {
            get {
                return ResourceManager.GetString("MoveIDUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move.svc/.
        /// </summary>
        internal static string MoveService {
            get {
                return ResourceManager.GetString("MoveService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account details successfully updated..
        /// </summary>
        internal static string msgAccountSuccessfullyUpdate {
            get {
                return ResourceManager.GetString("msgAccountSuccessfullyUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No alerts found.
        /// </summary>
        internal static string msgAlertNotfound {
            get {
                return ResourceManager.GetString("msgAlertNotfound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/json.
        /// </summary>
        internal static string msgAppJson {
            get {
                return ResourceManager.GetString("msgAppJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad Request.
        /// </summary>
        internal static string msgBadRequest {
            get {
                return ResourceManager.GetString("msgBadRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CVV is required..
        /// </summary>
        internal static string msgCardCCVIsRequired {
            get {
                return ResourceManager.GetString("msgCardCCVIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiry date is required..
        /// </summary>
        internal static string msgCardExpiryDateIsRequired {
            get {
                return ResourceManager.GetString("msgCardExpiryDateIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cardholder full name is required..
        /// </summary>
        internal static string msgCardFirstNameIsRequired {
            get {
                return ResourceManager.GetString("msgCardFirstNameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cardholder name is required..
        /// </summary>
        internal static string msgCardHolderNameIsRequired {
            get {
                return ResourceManager.GetString("msgCardHolderNameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cardholder full name is required..
        /// </summary>
        internal static string msgCardLastNameIsRequired {
            get {
                return ResourceManager.GetString("msgCardLastNameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card number is required..
        /// </summary>
        internal static string msgCardNumberIsRequired {
            get {
                return ResourceManager.GetString("msgCardNumberIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CVV value must be numeric..
        /// </summary>
        internal static string msgCCVValueIsNumeric {
            get {
                return ResourceManager.GetString("msgCCVValueIsNumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter correct password..
        /// </summary>
        internal static string msgCorrectPassword {
            get {
                return ResourceManager.GetString("msgCorrectPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter correct verification code..
        /// </summary>
        internal static string msgCorrectVerificationCode {
            get {
                return ResourceManager.GetString("msgCorrectVerificationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination address is required..
        /// </summary>
        internal static string msgCustomDestinationAddressIsRequired {
            get {
                return ResourceManager.GetString("msgCustomDestinationAddressIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Origin address is required..
        /// </summary>
        internal static string msgCustomOriginAddressIsRequired {
            get {
                return ResourceManager.GetString("msgCustomOriginAddressIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard dose not load..
        /// </summary>
        internal static string msgDashboardNotLoad {
            get {
                return ResourceManager.GetString("msgDashboardNotLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong!.
        /// </summary>
        internal static string msgDefaultServieMessage {
            get {
                return ResourceManager.GetString("msgDefaultServieMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is required..
        /// </summary>
        internal static string msgFieldRequired {
            get {
                return ResourceManager.GetString("msgFieldRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No contacts found.
        /// </summary>
        internal static string msgGetContactListForMoveNoContent {
            get {
                return ResourceManager.GetString("msgGetContactListForMoveNoContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Move..
        /// </summary>
        internal static string msgGetContactListForMoveNotFound {
            get {
                return ResourceManager.GetString("msgGetContactListForMoveNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact list is successfully retrieved..
        /// </summary>
        internal static string msgGetContactListForMoveOK {
            get {
                return ResourceManager.GetString("msgGetContactListForMoveOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer data is successfully retrieved..
        /// </summary>
        internal static string msgGetCustomerService {
            get {
                return ResourceManager.GetString("msgGetCustomerService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposit amount get successfully..
        /// </summary>
        internal static string msgGetDepositAmount {
            get {
                return ResourceManager.GetString("msgGetDepositAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to successful operation.
        /// </summary>
        internal static string msgGetDocumentService {
            get {
                return ResourceManager.GetString("msgGetDocumentService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to successful operation.
        /// </summary>
        internal static string msgGetEstimatePDF {
            get {
                return ResourceManager.GetString("msgGetEstimatePDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to successful operation.
        /// </summary>
        internal static string msgGetEstimateService {
            get {
                return ResourceManager.GetString("msgGetEstimateService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert list is successfully retrieved..
        /// </summary>
        internal static string msgGetListAlertService {
            get {
                return ResourceManager.GetString("msgGetListAlertService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Data is not found..
        /// </summary>
        internal static string msgGetMoveDataNotFound {
            get {
                return ResourceManager.GetString("msgGetMoveDataNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Data is successfully retrieved..
        /// </summary>
        internal static string msgGetMoveDataOk {
            get {
                return ResourceManager.GetString("msgGetMoveDataOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MoveID is successfully retrieved..
        /// </summary>
        internal static string msgGetMoveService {
            get {
                return ResourceManager.GetString("msgGetMoveService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Alert List..
        /// </summary>
        internal static string msgInvalidAlertList {
            get {
                return ResourceManager.GetString("msgInvalidAlertList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card number is invalid..
        /// </summary>
        internal static string msgInvalidCardNumber {
            get {
                return ResourceManager.GetString("msgInvalidCardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Customer.
        /// </summary>
        internal static string msgInvalidCustomer {
            get {
                return ResourceManager.GetString("msgInvalidCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Customer id.
        /// </summary>
        internal static string msgInvalidCustomerid {
            get {
                return ResourceManager.GetString("msgInvalidCustomerid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid document id.
        /// </summary>
        internal static string msgInvalidDocumentID {
            get {
                return ResourceManager.GetString("msgInvalidDocumentID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid email id..
        /// </summary>
        internal static string msgInvalidEmail {
            get {
                return ResourceManager.GetString("msgInvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service dates can not be less than or same as current date..
        /// </summary>
        internal static string msgInvalidServiceDate {
            get {
                return ResourceManager.GetString("msgInvalidServiceDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load date is required..
        /// </summary>
        internal static string msgLoadDateIsRequired {
            get {
                return ResourceManager.GetString("msgLoadDateIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery date is required..
        /// </summary>
        internal static string msgMoveDateIsRequired {
            get {
                return ResourceManager.GetString("msgMoveDateIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move is inactive..
        /// </summary>
        internal static string msgMoveIsNotActive {
            get {
                return ResourceManager.GetString("msgMoveIsNotActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposit amount not available..
        /// </summary>
        internal static string msgNoDepositFound {
            get {
                return ResourceManager.GetString("msgNoDepositFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Content.
        /// </summary>
        internal static string msgNoDocumentFound {
            get {
                return ResourceManager.GetString("msgNoDocumentFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment received successfully..
        /// </summary>
        internal static string msgNodusPaymentSuccessfull {
            get {
                return ResourceManager.GetString("msgNodusPaymentSuccessfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No estimate found.
        /// </summary>
        internal static string msgNoEstimateFound {
            get {
                return ResourceManager.GetString("msgNoEstimateFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hey, your move is awaiting approval from our coordinator. You will see the move information once it is approved..
        /// </summary>
        internal static string msgNoMoveForCustomer {
            get {
                return ResourceManager.GetString("msgNoMoveForCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You should agree the terms to continue further..
        /// </summary>
        internal static string msgNotAgree {
            get {
                return ResourceManager.GetString("msgNotAgree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email id does not exist in the system..
        /// </summary>
        internal static string msgNotExistEmailId {
            get {
                return ResourceManager.GetString("msgNotExistEmailId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pack date is required..
        /// </summary>
        internal static string msgPackDateIsRequired {
            get {
                return ResourceManager.GetString("msgPackDateIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pack date must be less than load date..
        /// </summary>
        internal static string msgPackdatemustbelessthanloaddate {
            get {
                return ResourceManager.GetString("msgPackdatemustbelessthanloaddate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pack date must be less than delivery date..
        /// </summary>
        internal static string msgPackdatemustbelessthanmovedate {
            get {
                return ResourceManager.GetString("msgPackdatemustbelessthanmovedate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password does not match..
        /// </summary>
        internal static string msgPasswordMismatch {
            get {
                return ResourceManager.GetString("msgPasswordMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved.
        /// </summary>
        internal static string msgPaymentApproved {
            get {
                return ResourceManager.GetString("msgPaymentApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to process payment with our payment gateway provider..
        /// </summary>
        internal static string msgPaymentRequestFail {
            get {
                return ResourceManager.GetString("msgPaymentRequestFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no move available for this customer..
        /// </summary>
        internal static string msgPendingMove {
            get {
                return ResourceManager.GetString("msgPendingMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number is required..
        /// </summary>
        internal static string msgPhoneNumberIsRequired {
            get {
                return ResourceManager.GetString("msgPhoneNumberIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid phone no..
        /// </summary>
        internal static string msgPleaseEnterValidPhoneNo {
            get {
                return ResourceManager.GetString("msgPleaseEnterValidPhoneNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select load date greater than or equal delivery date..
        /// </summary>
        internal static string msgPleaseSelectLoadDateGreaterThanorEqualMoveDate {
            get {
                return ResourceManager.GetString("msgPleaseSelectLoadDateGreaterThanorEqualMoveDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select pack date greater than load date..
        /// </summary>
        internal static string msgPleaseSelectPackDateGraterThanLoadDate {
            get {
                return ResourceManager.GetString("msgPleaseSelectPackDateGraterThanLoadDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alerts found. Data was successfully retrieved..
        /// </summary>
        internal static string msgPostAlertService {
            get {
                return ResourceManager.GetString("msgPostAlertService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer data is successfully created..
        /// </summary>
        internal static string msgPostCustomerService {
            get {
                return ResourceManager.GetString("msgPostCustomerService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to successful operation.
        /// </summary>
        internal static string msgPostPaymentTransaction {
            get {
                return ResourceManager.GetString("msgPostPaymentTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert list is successfully updated..
        /// </summary>
        internal static string msgPutAlertService {
            get {
                return ResourceManager.GetString("msgPutAlertService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment updated successfully..
        /// </summary>
        internal static string msgPutAmount {
            get {
                return ResourceManager.GetString("msgPutAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer data is successfully updated..
        /// </summary>
        internal static string msgPutCustomerService {
            get {
                return ResourceManager.GetString("msgPutCustomerService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to successful operation..
        /// </summary>
        internal static string msgPutEstimateData {
            get {
                return ResourceManager.GetString("msgPutEstimateData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Move.
        /// </summary>
        internal static string msgPutMoveDataNotFound {
            get {
                return ResourceManager.GetString("msgPutMoveDataNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MoveID is successfully updated..
        /// </summary>
        internal static string msgPutMoveDataOK {
            get {
                return ResourceManager.GetString("msgPutMoveDataOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No such estimate available.
        /// </summary>
        internal static string msgPutNoEstimateFound {
            get {
                return ResourceManager.GetString("msgPutNoEstimateFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification code must be in 6-digit..
        /// </summary>
        internal static string msgRequired6digitVerificationCode {
            get {
                return ResourceManager.GetString("msgRequired6digitVerificationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password .
        /// </summary>
        internal static string msgRequiredConfirmPassword {
            get {
                return ResourceManager.GetString("msgRequiredConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create password .
        /// </summary>
        internal static string msgRequiredCreatePassword {
            get {
                return ResourceManager.GetString("msgRequiredCreatePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email id.
        /// </summary>
        internal static string msgRequiredEmailId {
            get {
                return ResourceManager.GetString("msgRequiredEmailId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @fieldName is required..
        /// </summary>
        internal static string msgRequiredField {
            get {
                return ResourceManager.GetString("msgRequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string msgRequiredPassword {
            get {
                return ResourceManager.GetString("msgRequiredPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your 6-digit verification code..
        /// </summary>
        internal static string msgRequiredVerificationCode {
            get {
                return ResourceManager.GetString("msgRequiredVerificationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal Server Error.
        /// </summary>
        internal static string msgServiceUnavailable {
            get {
                return ResourceManager.GetString("msgServiceUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to successful operation..
        /// </summary>
        internal static string msgSuccessfullOperation {
            get {
                return ResourceManager.GetString("msgSuccessfullOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unregistered customer.
        /// </summary>
        internal static string msgUnregisteredCustomer {
            get {
                return ResourceManager.GetString("msgUnregisteredCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost value must be numeric..
        /// </summary>
        internal static string msgvaluationCostValueIsNumeric {
            get {
                return ResourceManager.GetString("msgvaluationCostValueIsNumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost value is required..
        /// </summary>
        internal static string msgvaluationCostValueIsRequired {
            get {
                return ResourceManager.GetString("msgvaluationCostValueIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Declared value must be numeric..
        /// </summary>
        internal static string msgvaluationDeclaredValueIsNumeric {
            get {
                return ResourceManager.GetString("msgvaluationDeclaredValueIsNumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Declared value is required..
        /// </summary>
        internal static string msgvaluationDeclaredValueIsRequired {
            get {
                return ResourceManager.GetString("msgvaluationDeclaredValueIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coverage value is required..
        /// </summary>
        internal static string msgvaluationDeductibleIsRequired {
            get {
                return ResourceManager.GetString("msgvaluationDeductibleIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification code is expired..
        /// </summary>
        internal static string msgVerificationcodeisexpired {
            get {
                return ResourceManager.GetString("msgVerificationcodeisexpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification is required.
        /// </summary>
        internal static string msgVerificationRequired {
            get {
                return ResourceManager.GetString("msgVerificationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What matters most is required..
        /// </summary>
        internal static string msgWhatMattersMostIsRequired {
            get {
                return ResourceManager.GetString("msgWhatMattersMostIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to document.svc/{0}/pdf.
        /// </summary>
        internal static string MyDocumentPdfService {
            get {
                return ResourceManager.GetString("MyDocumentPdfService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to document.svc/list/{0}.
        /// </summary>
        internal static string MyDocumentService {
            get {
                return ResourceManager.GetString("MyDocumentService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a3eef35e-02d9-48f8-977c-cc0dc8df1cb6|1rivet123.
        /// </summary>
        internal static string NodusPayFabricDeviceAuthorization {
            get {
                return ResourceManager.GetString("NodusPayFabricDeviceAuthorization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://sandbox.payfabric.com/v2/rest/api/token/create.
        /// </summary>
        internal static string NodusPayFabricTokenUrl {
            get {
                return ResourceManager.GetString("NodusPayFabricTokenUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://sandbox.payfabric.com/V2/Rest/api/transaction/process.
        /// </summary>
        internal static string NodusPayFabricTransactionProcessUrl {
            get {
                return ResourceManager.GetString("NodusPayFabricTransactionProcessUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USD.
        /// </summary>
        internal static string PaymentCurrency {
            get {
                return ResourceManager.GetString("PaymentCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AuthorizeNetSandbox.
        /// </summary>
        internal static string PaymentGatewaySetupID {
            get {
                return ResourceManager.GetString("PaymentGatewaySetupID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale.
        /// </summary>
        internal static string PaymentTransactionType {
            get {
                return ResourceManager.GetString("PaymentTransactionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}Payment.svc/Transaction.
        /// </summary>
        internal static string PostPaymentTransactionUrl {
            get {
                return ResourceManager.GetString("PostPaymentTransactionUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Document/DOCVAL003/pdf.
        /// </summary>
        internal static string PrivacyPolicyPdfUrl {
            get {
                return ResourceManager.GetString("PrivacyPolicyPdfUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment.svc/amount.
        /// </summary>
        internal static string PutAmountServiceUrl {
            get {
                return ResourceManager.GetString("PutAmountServiceUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^4[0-9]{6,}$.
        /// </summary>
        internal static string VisaCardTypeRegex {
            get {
                return ResourceManager.GetString("VisaCardTypeRegex", resourceCulture);
            }
        }
    }
}
